env: ${ENV}

#########################################################
# Database
#########################################################

database:
  user: ${DATABASE_USER}
  password: ${DATABASE_PASSWORD}
  host: ${DATABASE_HOST}
  port: ${DATABASE_PORT}
  name: ${DATABASE_NAME}

#########################################################
# Storage
#########################################################

s3:
  access_key: ${S3_ACCESS_KEY}
  secret_key: ${S3_SECRET_KEY}
  region: ${S3_REGION}
  bucket_name: ${S3_BUCKET_NAME}

minio:
  endpoint_url: ${MINIO_HOST}:${MINIO_PORT}
  access_key: ${MINIO_ACCESS_KEY}
  secret_key: ${MINIO_SECRET_KEY}
  bucket_name: ${MINIO_BUCKET_NAME}

#########################################################
# Messaging
#########################################################

sqs:
  region: ${AWS_SQS_REGION}
  access_key: ${AWS_SQS_ACCESS_KEY}
  secret_key: ${AWS_SQS_SECRET_KEY}
  queue: ${AWS_SQS_QUEUE}
